# Generated by Django 3.0.5 on 2020-04-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('hospitalname', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'hospitalinfo',
            },
        ),
        migrations.CreateModel(
            name='ishospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('hospital', models.BooleanField()),
            ],
            options={
                'db_table': 'ishospital',
            },
        ),
    ]
